Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/SpaceInsideSquareBrackets:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
