AllCops:
  NewCops: enable

Lint/AssignmentInCondition: { Enabled: no }
Metrics/AbcSize: { Enabled: no }
Metrics/ClassLength: { Enabled: no }
Metrics/CyclomaticComplexity: { Enabled: no }
Metrics/MethodLength: { Enabled: no }
Metrics/PerceivedComplexity: { Enabled: no }
Style/FrozenStringLiteralComment: { Enabled: no }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: consistent_comma }
