AllCops: {TargetRubyVersion: 2.4}
Lint/AssignmentInCondition: {Enabled: false}
Metrics/BlockLength: {Enabled: false}
Metrics/ClassLength: {Enabled: false}
Metrics/LineLength: {Enabled: false}
Metrics/MethodLength: {Enabled: false}
Style/BlockDelimiters: {Enabled: false}
Style/Documentation: {Enabled: false}
Style/FrozenStringLiteralComment: {Enabled: false}
Style/GuardClause: {Enabled: false}
Style/IfUnlessModifier: {Enabled: false}
Style/Lambda: {Enabled: false}
Style/MultilineMethodCallIndentation: {Enabled: false}
Style/NegatedIf: {Enabled: false}
Style/ParallelAssignment: {Enabled: false}
Style/RedundantException: {Enabled: false}
Style/SpaceBeforeBlockBraces: {Enabled: false}
Style/SpaceInLambdaLiteral: {Enabled: false}
Style/SpaceInsideBlockBraces: {Enabled: false}
Style/SpaceInsideBrackets: {Enabled: false}
Style/SpaceInsideSquareBrackets: {Enabled: false}
Style/StringLiterals: {Enabled: false}
Style/TrailingCommaInArguments: {Enabled: false}
Style/TrailingCommaInLiteral: {Enabled: false}
Style/WordArray: {Enabled: false}
