# Install xremap for KDE/Wayland:
#
#   cargo install xremap --features kde
#
# Give user non-root access to input devices if necessary (reboot required after this):
#
#   sudo gpasswd -a $USER input
#   echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules
#
# Run it:
#
#   xremap --watch=config -- ~/.xremap.yml
#
# References:
#
# - https://github.com/k0kubun/xremap
# - https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#L26-L572

keymap:
  - application: { only: firefox }
    exact_match: true
    remap:
      Alt_L-0: Ctrl-0 # zoom reset
      Alt_L-A: Ctrl-A # select all
      Alt_L-Backspace: Ctrl-Backspace # delete word back
      Alt_L-C: Ctrl-C # copy
      Alt_L-Equal: Ctrl-Equal # zoom in
      Alt_L-F: Ctrl-F # find
      Alt_L-L: Ctrl-L # select address bar
      Alt_L-Left: Super-Left # history back
      Alt_L-Minus: Ctrl-Minus # zoom in
      Alt_L-R: Ctrl-R # reload
      Alt_L-Right: Super-Right # history forward
      Alt_L-Shift-C: Ctrl-Shift-C # inspect
      Alt_L-Shift-LeftBrace: Ctrl-PageUp # prev tab
      Alt_L-Shift-P: Ctrl-Shift-P # private window
      Alt_L-Shift-R: Ctrl-Shift-R # hard reload
      Alt_L-Shift-RightBrace: Ctrl-PageDown # next tab
      Alt_L-Shift-T: Ctrl-Shift-T # reopen tab
      Alt_L-T: Ctrl-T # new tab
      Alt_L-V: Ctrl-V # paste
      Alt_L-W: Ctrl-W # close tab
      Alt_L-X: Ctrl-X # cut

  - application: { only: konsole }
    exact_match: true
    remap:
      Alt_L-C: Ctrl-Shift-C # copy
      Alt_L-D: Ctrl-Shift-0 # split pane horizontally
      Alt_L-Equal: Ctrl-Equal # zoom in
      Alt_L-F: Ctrl-Shift-F # find
      Alt_L-Minus: Ctrl-Minus # zoom out
      Alt_L-N: Ctrl-Shift-N # new window
      Alt_L-Shift-D: Ctrl-Shift-9 # split pane vertically
      Alt_L-V: Ctrl-Shift-V # paste
      Alt_L-R: [Grave, V, Grave, Ctrl-Super-E] # insert current line from IDE
      Alt_L-E: Ctrl-Super-E # expand current line

  - application: { only: discord }
    exact_match: true
    remap:
      Alt_L-A: Ctrl-A # select all
      Alt_L-Backspace: Ctrl-Backspace # delete word back
      Alt_L-C: Ctrl-C # copy
      Alt_L-F: Ctrl-F # find
      Alt_L-Left: Ctrl-Left # word left
      Alt_L-Right: Ctrl-Right # word right
      Alt_L-V: Ctrl-V # paste
      Alt_L-X: Ctrl-X # cut

  - application: { only: "net.code-industry.masterpdfeditor5" }
    exact_match: true
    remap:
      Alt_L-A: Ctrl-A # select all
      Alt_L-Backspace: Ctrl-Backspace # delete word back
      Alt_L-C: Ctrl-C # copy
      Alt_L-F: Ctrl-F # find
      Alt_L-V: Ctrl-V # paste
      Alt_L-X: Ctrl-X # cut
      Alt_L-Y: Ctrl-Y # redo
      Alt_L-Z: Ctrl-Z # undo
      Alt_L-Equal: Ctrl-Shift-Equal # zoom in
      Alt_L-Minus: Ctrl-Minus # zoom out
      Alt_L-0: Ctrl-0 # zoom reset

  - application: { only: obsidian }
    exact_match: true
    remap:
      Alt_L-A: Ctrl-A # select all
      Alt_L-Backspace: Ctrl-Backspace # delete word back
      Alt_L-C: Ctrl-C # copy
      Alt_L-V: Ctrl-V # paste
      Alt_L-W: Ctrl-W # close tab
      Alt_L-X: Ctrl-X # cut
      Alt_L-Y: Ctrl-Y # redo
      Alt_L-Z: Ctrl-Z # undo
      Alt_L-P: Ctrl-P # command palette

  - application: { only: obsidian }
    remap:
      Alt_L-Left: Ctrl-Left # word left
      Alt_L-Right: Ctrl-Right # word right
      Alt_L-Up: Ctrl-Up # paragraph up
      Alt_L-Down: Ctrl-Down # paragraph down

  - application: { only: spotify }
    remap:
      Alt_L-F: Ctrl-F # find
      Alt_L-A: Ctrl-A # select all

  - application: { only: gvim }
    exact_match: true
    remap:
      Alt_L-A: Ctrl-Super-A
      Alt_L-B: Ctrl-Super-B
      Alt_L-C: Ctrl-Super-C
      Alt_L-Equal: Ctrl-Super-Equal # zoom in
      Alt_L-Minus: Ctrl-Super-Minus # zoom out
      Alt_L-O: Ctrl-Super-O
      Alt_L-P: Ctrl-Super-P
      Alt_L-R: Ctrl-Super-R
      Alt_L-S: Ctrl-Super-S
      Alt_L-Slash: Ctrl-Super-Slash
      Alt_L-V: Ctrl-Super-V
      Alt_L-X: Ctrl-Super-X
      Alt_L-Z: Ctrl-Super-Z
      Alt_L-W: Ctrl-Super-W
