- name: irssi
  hosts: all

  vars:
    username: "{{ lookup('env', 'USER') }}"

  tasks:
  - name: irssi package
    apt: pkg=irssi

  - name: irssi config
    local_action: >
      command rsync
      -e 'ssh -o stricthostkeychecking=no -o userknownhostsfile=/dev/null -o batchmode=yes -o passwordauthentication=no'
      --delete
      -uaSHAXEx
      files/irssi/
      {{inventory_hostname}}:/home/{{username}}/.irssi/
